import { SourceSans } from "./assets/fonts/SourceSans"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={SourceSans.className}>
        <div>{children}</div>
      </body>
    </html>
  )
}
